export const COLORS = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
    boxShadow:'#63636333',
};

export const Items = [
    {
        id: 1,
        category: 'product',
        productName: 'Apple Watch Series 9 GPS & Cellular 45mm (Midnight Strap, Free Size)',
        rating: '4.6',
        productPrice: '44,999',
        description: 'Apple Watch Series 9 helps you stay connected, active, healthy, and safe. Featuring double tap, a magical way to interact with Apple Watch, and an even-brighter display.',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/apple-main.png'),
        isAvailable: true,
        productImageList: [
        require('../database/images/products/apple-one.png'),
        require('../database/images/products/apple-two.png'),
        require('../database/images/products/apple-three.png'),
        require('../database/images/products/apple-four.png'),
        ],
    },
    {
        id: 2,
        category: 'product',
        productName: 'Canon EOS 3000D DSLR Camera 1 Camera Body, 18 - 55 mm Lens  (Black)',
        rating: '4.4',
        productPrice: '30,990',
        description:'If you are a photography enthusiast, then the Canon EOS 3000D DSLR Camera is a must-have gadget. Featuring an 18 MP (APS-C) CMOS sensor and the DIGIC 4+ imaging processor, you can capture amazing photos of your subject at all times, even in low-light conditions. Moreover, the remote Live View function lets you control this camera remotely using your smartphone so you can capture amazing photos even from a distance.',
        isOff: false,
        productImage: require('../database/images/products/camera-main.png'),
        isAvailable: true,
        productImageList: [
        require('../database/images/products/camera-one.png'),
        require('../database/images/products/camera-two.png'),
        require('../database/images/products/camera-three.png'),
        require('../database/images/products/camera-four.png'),
        ],
    },
    {
        id: 3,
        category: 'accessory',
        productName: 'boAt Airdopes 441',
        productPrice: 1999,
        description:
            'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
        isOff: true,
        offPercentage: 18,
        productImage: require('../database/images/accessories/boatairpods1.png'),
        isAvailable: true,
        productImageList: [
        require('../database/images/accessories/boatairpods1.png'),
        require('../database/images/accessories/boatairpods2.png'),
        require('../database/images/accessories/boatairpods3.png'),
        ],
    },
    {
        id: 4,
        category: 'accessory',
        productName: 'boAt Bassheads 242',
        productPrice: 399,
        description:
        'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
        isOff: false,
        productImage: require('../database/images/accessories/boatbassheads1.png'),
        isAvailable: true,
        productImageList: [
        require('../database/images/accessories/boatbassheads1.png'),
        require('../database/images/accessories/boatbassheads2.png'),
        require('../database/images/accessories/boatbassheads3.png'),
        ],
    },
    {
        id: 5,
        category: 'accessory',
        productName: 'boAt Rockerz 255 Pro+',
        productPrice: 1499,
        description:
        'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
        isOff: false,
        productImage: require('../database/images/accessories/boatrockerz1.png'),
        isAvailable: false,
        productImageList: [
        require('../database/images/accessories/boatrockerz1.png'),
        require('../database/images/accessories/boatrockerz2.png'),
        require('../database/images/accessories/boatrockerz3.png'),
        ],
    },
    {
        id: 6,
        category: 'accessory',
        productName: 'Boult Audio AirBass Propods TWS',
        productPrice: 1299,
        description:
        'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
        isOff: false,
        productImage: require('../database/images/accessories/boultairbass1.png'),
        isAvailable: true,
        productImageList: [
        require('../database/images/accessories/boultairbass1.png'),
        require('../database/images/accessories/boultairbass2.png'),
        require('../database/images/accessories/boultairbass3.png'),
        ],
    },
];